### ISSUE TITLE
Lack of Support for Viewing Content in Dark Mode for Black Theme or Plugins

### ISSUE THREAD

**Issue by dariopiyush** [caponetto/vscode-diff-viewer#103]
At present, there is no available method or plugin support to view content in dark mode when using the Black theme in the VS Code extension. This limitation makes it difficult to work efficiently, especially for users who prefer or are accustomed to dark-themed environments, as the content appears unreadable or visually straining.

I would like to request the addition of a dark mode support feature or a compatible plugin that enhances the visibility of content while using the Black theme. The feature should ensure that text and UI elements are clearly distinguishable and easy to read, while maintaining the overall aesthetics of a dark mode environment.

**Comment by caponetto** [comment]
Hi @dariopiyush. There is an option on the extension settings to change the color scheme.

<img width="411" alt="image" src="https://github.com/user-attachments/assets/5a8d48c2-aeb3-40fb-8f84-f7880500cd38">

**Comment by caponetto** [comment]
I'm closing it due to inactivity. Feel free to reopen this issue with more information if it is not resolved.
