### ISSUE TITLE
Setting Diff Viewer as the Default doesn't work with another extension

### ISSUE THREAD

**Issue by ADTC** [caponetto/vscode-diff-viewer#26]
When in the quick picker, I chose _"Configure default editor for '*.diff'..."_ and chose Diff Viewer. Now the quick picker says that Diff Viewer is default. But still, `*.diff` files are opening in the Text Editor anyway.

How do I force it to always render in Diff Viewer? Does this have something to do with the view being read-only?

Side-note: Git can generate diff in `*.patch` files. Worth including this file extension as well.

_PS: Ignore the mention below, and continue with next comment._

**Comment by ADTC** [comment]
I have completely misunderstood the problem here. Actually, it works correctly when I choose the file in the Explorer pane or open it normally.

The problem is with [this extension vscode-diff](https://marketplace.visualstudio.com/items?itemName=huytd.vscode-diff). The code forcefully opens the text editor on the generated diff file (see code below). _Note that I amended the extension to generate a .diff file instead of .patch file as per huytd/vscode-diff#1._

[vscode-diff lines 29-30:](https://github.com/huytd/vscode-diff/blob/master/src/extension.ts#L29-L30)
```
		const doc = await vscode.workspace.openTextDocument(uri);
		await vscode.window.showTextDocument(doc, { preview: false });
```
Is there any way I can force that extension to open the file in Diff Viewer instead (maybe by changing the code above)?

I saw in VS Code API that there is an openCustomDocument method in [CustomEditorProvider](https://code.visualstudio.com/api/references/vscode-api#CustomEditorProvider%3CT%3E) and [CustomReadonlyEditorProvider](https://code.visualstudio.com/api/references/vscode-api#CustomReadonlyEditorProvider%3CT%3E). How to implement it?

**Comment by caponetto** [comment]
Hi @ADTC,

One manual way would be to right-click on the file tab and use the _Reopen Editor With..._ option.
If you want an automatic way, I think you need to change that code you've shown to something like:
```ts
vscode.commands.executeCommand("vscode.openWith", uri, "diffViewer");
```

**Comment by ADTC** [comment]
Nearly perfect! That works. There's only one problem. If the diff is already open, it doesn't reload to show the new changes.

(Short of generating random file names,) Is there a way to force reload if the file is already open? Or to close that tab automatically first if it's open.

**Comment by caponetto** [comment]
I'm not sure if there's a reopen command or something like that but here's another possibility that might work:
```ts
vscode.window
    .showTextDocument(uri) // open or focus if the uri is already open
    .then(() => vscode.commands.executeCommand("workbench.action.closeActiveEditor")) // close it
    .then(() => vscode.commands.executeCommand("vscode.openWith", uri, "diffViewer")); // open with diffViewer
```

**Comment by ADTC** [comment]
Suspecting it may not work, as my investigation earlier showed that the _Diff Viewer_ tabs don't even show up in the list of Text Documents. Perhaps because it's a custom document, any API acting on text documents won't work.

Anyway I'm happy with the current solution in my PR ADTC/vscode-diff#1 and I'll revisit this if my needs change. Thank you so much for your input!

**Comment by caponetto** [comment]
Great! :)
