### ISSUE TITLE
"No diff structure found in" with non-utf8 encodings

### ISSUE THREAD

**Issue by domgenv** [caponetto/vscode-diff-viewer#37]
Thanks for making this extension!

It looks like this extension will only work with files encoded with utf8. If you use a different type it will say, "No diff structure found in (file)". I had to resave my file with UTF-8 in order to see the custom view.

I'm not very familiar with extension development but it seems like this section of code in DiffDocument.ts would need to detect the appropriate Decoder before it sets up the DiffDocument. I'm not sure off-hand how to do that. I'll see if I can find out.

![image](https://user-images.githubusercontent.com/53090700/141578956-41b046cf-a991-416f-8e2c-5e5af7fb7e19.png)

**Comment by caponetto** [comment]
Hi @domgenv, thanks for bringing this up!
Would you mind sharing a file where this behavior is reproducible?

**Comment by domgenv** [comment]
Sure, no problem! It looks like github won't accept a file with .diff so I added .txt at the end. In VSCode it shows the file has encoding "UTF-16 LE".

[changes.diff.txt](https://github.com/caponetto/vscode-diff-viewer/files/7539981/changes.diff.txt)

**Comment by Cussa** [comment]
Hi, do you have any updates regarding this issue? It seems that still have the problems with files with other encodings.

**Comment by caponetto** [comment]
Hi @Cussa, the issue hasn't been fixed yet. Feel free to send a PR :)

**Comment by caponetto** [comment]
Fixed on `v1.2.0`
