### ISSUE TITLE
line numbers columns shifted to the side

### ISSUE THREAD

**Issue by jacekkopecky** [caponetto/vscode-diff-viewer#73]
Hi, sometimes on Mac and always on Windows my diffs show like this:

<img width="612" alt="Screen Shot 2023-02-28 at 22 24 37" src="https://user-images.githubusercontent.com/807315/222239666-0550a2ff-e548-48b5-a407-3fcdda78b684.png">

Notice how the columns that have line numbers are off by about a character.

I believe the problem is [app.css line 9](https://github.com/caponetto/vscode-diff-viewer/blob/main/src/webview/css/static/app.css#L9) - I don't think you need "both-edges" there.

**Comment by caponetto** [comment]
Good catch, @jacekkopecky! I will send a PR.
