### ISSUE TITLE
How to ?  (newer versions are missing select for Compare menu option)

### ISSUE THREAD

**Issue by inspectionsbybob** [caponetto/vscode-diff-viewer#78]
Ok, I recently moved computers and had to reload everything, so my old configs that worked easy disappeared.

I downloaded VS 1.76 and Diff Viewer and can't find the "Open for Comparison" menu choice...

So rather than get frustrated, I will ask.... How do I compare two folders/files?

I have TWO libraries I want to compare

"VSStuff/Marlin Bug Fix"  and "VSStuff/Iliam"

I want to compare those two builds, probably starting with the "Config.H" files....

How do I open those two to compare them??   I open the files/folders. but never see the "select for compare" options...

H E L P ??

**Comment by inspectionsbybob** [comment]
I have been playing more, I can get One file open for compare, but everythime I try to open the second file, it flips to that file and I still only have one file open.

I can't figure out how to get BOTH files open, and be able to do it again if I do get it once...

**Comment by jacekkopecky** [comment]
@inspectionsbybob I believe you mean a different package that allows you to compare two files, such as `fabiospampinato.vscode-diff` (called simply Diff in the extensions list). 

The package here, `caponetto.vscode-diff-viewer`, i.e. Diff Viewer, lets you open existing diff files, not showing the differences between two selected files.

**Comment by inspectionsbybob** [comment]
OK, I will have to go get the "other" diff....
Before I switched computers, it was easy to open to files in the editor, and then select them to compare...done...

Trying to get back to that....

**Comment by jacekkopecky** [comment]
@inspectionsbybob please let me know when you find what it was

**Comment by inspectionsbybob** [comment]
It has something to do with opening the editor and THEN doing a file open... open file will not show in file explorer, you need both the editor and the explorer open before "select to compare" will show up...
