### ISSUE TITLE
Is it possible to change the diff colours?

### ISSUE THREAD

**Issue by yushiyangk** [caponetto/vscode-diff-viewer#96]
I find the yellow used to highlight lines with word diffs to be quite confusing.

I worked around it by using side-by-side diffs instead (where it is highlighted in green), but ideally I would like to adjust the colours to match VS Code's built-in diff view, if that's possible?

Also should the colours be synced between the line-by-line and side-by-side views?

**Comment by caponetto** [comment]
The colors come from the diff2html library (see a demo at https://diff2html.xyz/demo.html).
If you believe the colors should be different, you can discuss and possibly contribute to their repository at https://github.com/rtfpessoa/diff2html

**Comment by yushiyangk** [comment]
Does that mean that the side-by-side view is unrelated to diff2html?
